"""Added a scheduler job store

Revision ID: be7f3eb3d2bb
Revises: 9ed73f223253
Create Date: 2020-07-24 10:37:54.188722

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be7f3eb3d2bb'
down_revision = '9ed73f223253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time',
                  table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
                    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False,
                              nullable=False),
                    sa.Column('next_run_time',
                              postgresql.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=True),
                    sa.Column('job_state', postgresql.BYTEA(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
                    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs',
                    ['next_run_time'], unique=False)
    # ### end Alembic commands ###
